export const productData = [
  {
    id: 1,
    name: "Ahmet",
    surname: "Yılmaz",
    city: "İstanbul",
    imageUrl: "https://randomuser.me/api/portraits/men/1.jpg",
  },
  {
    id: 2,
    name: "Ayşe",
    surname: "Kaya",
    city: "Ankara",
    imageUrl: "https://randomuser.me/api/portraits/women/1.jpg",
  },
  {
    id: 3,
    name: "Mehmet",
    surname: "Demir",
    city: "İzmir",
    imageUrl: "https://randomuser.me/api/portraits/men/2.jpg",
  },
  {
    id: 4,
    name: "Fatma",
    surname: "Çelik",
    city: "Bursa",
    imageUrl: "https://randomuser.me/api/portraits/women/2.jpg",
  },
  {
    id: 5,
    name: "Mustafa",
    surname: "Şahin",
    city: "Antalya",
    imageUrl: "https://randomuser.me/api/portraits/men/3.jpg",
  },
  {
    id: 6,
    name: "Zeynep",
    surname: "Öztürk",
    city: "Bodrum",
    imageUrl: "https://randomuser.me/api/portraits/women/3.jpg",
  },
  {
    id: 7,
    name: "Ali",
    surname: "Aydın",
    city: "İstanbul",
    imageUrl: "https://randomuser.me/api/portraits/men/4.jpg",
  },
  {
    id: 8,
    name: "Emine",
    surname: "Yıldız",
    city: "Ankara",
    imageUrl: "https://randomuser.me/api/portraits/women/4.jpg",
  },
  {
    id: 9,
    name: "Hüseyin",
    surname: "Arslan",
    city: "İzmir",
    imageUrl: "https://randomuser.me/api/portraits/men/5.jpg",
  },
  {
    id: 10,
    name: "Hatice",
    surname: "Erdoğan",
    city: "Bodrum",
    imageUrl: "https://randomuser.me/api/portraits/women/5.jpg",
  },
  {
    id: 11,
    name: "İbrahim",
    surname: "Güneş",
    city: "Muğla",
    imageUrl: "https://randomuser.me/api/portraits/men/6.jpg",
  },
  {
    id: 12,
    name: "Elif",
    surname: "Kurt",
    city: "Bodrum",
    imageUrl: "https://randomuser.me/api/portraits/women/6.jpg",
  },
  {
    id: 13,
    name: "Murat",
    surname: "Özdemir",
    city: "İstanbul",
    imageUrl: "https://randomuser.me/api/portraits/men/7.jpg",
  },
  {
    id: 14,
    name: "Zehra",
    surname: "Koç",
    city: "Ankara",
    imageUrl: "https://randomuser.me/api/portraits/women/7.jpg",
  },
  {
    id: 15,
    name: "Ömer",
    surname: "Doğan",
    city: "İzmir",
    imageUrl: "https://randomuser.me/api/portraits/men/8.jpg",
  },
  {
    id: 16,
    name: "Merve",
    surname: "Özkan",
    city: "Bodrum",
    imageUrl: "https://randomuser.me/api/portraits/women/8.jpg",
  },
  {
    id: 17,
    name: "Osman",
    surname: "Aslan",
    city: "Antalya",
    imageUrl: "https://randomuser.me/api/portraits/men/9.jpg",
  },
  {
    id: 18,
    name: "Esra",
    surname: "Kılıç",
    city: "Muğla",
    imageUrl: "https://randomuser.me/api/portraits/women/9.jpg",
  },
  {
    id: 19,
    name: "Yusuf",
    surname: "Çetin",
    city: "İstanbul",
    imageUrl: "https://randomuser.me/api/portraits/men/10.jpg",
  },
  {
    id: 20,
    name: "Selin",
    surname: "Yalçın",
    city: "Bodrum",
    imageUrl: "https://randomuser.me/api/portraits/women/10.jpg",
  },
  {
    id: 21,
    name: "Emre",
    surname: "Aktaş",
    city: "Ankara",
    imageUrl: "https://randomuser.me/api/portraits/men/11.jpg",
  },
  {
    id: 22,
    name: "Büşra",
    surname: "Korkmaz",
    city: "İzmir",
    imageUrl: "https://randomuser.me/api/portraits/women/11.jpg",
  },
  {
    id: 23,
    name: "Can",
    surname: "Özer",
    city: "Bodrum",
    imageUrl: "https://randomuser.me/api/portraits/men/12.jpg",
  },
  {
    id: 24,
    name: "Derya",
    surname: "Şen",
    city: "Muğla",
    imageUrl: "https://randomuser.me/api/portraits/women/12.jpg",
  },
  {
    id: 25,
    name: "Burak",
    surname: "Acar",
    city: "İstanbul",
    imageUrl: "https://randomuser.me/api/portraits/men/13.jpg",
  },
  // Continue with remaining entries...
  {
    id: 100,
    name: "Deniz",
    surname: "Yalın",
    city: "Bodrum",
    imageUrl: "https://randomuser.me/api/portraits/women/50.jpg",
  },
];
